### PR TITLE
GitLab 8.14, GitLab Shell 4.0.2, migration to GitLab Workhorse, other fixes

### PR DESCRIPTION
**Pull request by chewi**
The headline change here is the upgrade and the GitLab Workhorse migration but that mostly speaks for itself. `gitlab.yml` has seen significant changes and some of the attributes are no longer relevant as they are now managed within the web interface.

MySQL is currently broken (in current master) as mentioned in #95. I tried very hard to fix it and had it worked out on our side but problems with the mysql cookbook got in the way. Since I don't use MySQL, I had to give up and test with PostgreSQL instead.

I have applied this update to our production server, with some inevitable manual twiddling, and it's looking good so far.

### CODE REVIEW

**Comment by chewi** [comment]
Bad news, merging branches is not working, most likely because git is now much too old on CentOS 7. I will investigate the options.

**Comment by chewi** [comment]
I have now dealt with this and merging works again. I wanted to avoid building from source where possible so I put in some `value_for_platform` logic and used the End Point repository for RHEL 7.

**Comment by atomic-penguin** [comment]
@chewi, I am not actively using or maintaining this code any longer.  I've made you a collaborator, if you wish to manage PRs or issues.

**Comment by chewi** [comment]
Many thanks for that. I'm a little apprehensive about merging this as the upgrade isn't exactly seamless but then again, it never was. I think it gets us to a better place overall. I'll try to do something about MySQL before the next release but my time is limited too.

**Pull request merged**
